version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: shared_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_NOTIFY_NATS_ENABLE: "on"
      MINIO_NOTIFY_NATS_ADDRESS: "nats:4222"
      MINIO_NOTIFY_NATS_SUBJECT: "minio.events"
      MINIO_NOTIFY_NATS_USERNAME: ""
      MINIO_NOTIFY_NATS_PASSWORD: ""
      MINIO_NOTIFY_NATS_JETSTREAM_ENABLE: "on"
      MINIO_NOTIFY_NATS_STREAM: "MINIO_EVENTS"
      MINIO_NOTIFY_NATS_TLS: "off"
    volumes:
      - C:/Users/buith_ejh62q2/Desktop/minio/data:/data
    command: server /data --console-address ":9001"
    depends_on:
      - nats
  minio-mc:
    image: minio/mc
    container_name: minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set myminio http://minio:9000 minioadmin minioadmin123; do
        echo 'Waiting for MinIO...'
        sleep 1
      done;
      
      # Create bucket if not exist
      mc mb myminio/bbmovie-raw || true;
      mc mb myminio/bbmovie-hls || true;
      mc mb myminio/bbmovie-secure || true;
      mc mb myminio/bbmovie-public || true;
      
      # Allow everyone to download the file
      mc anonymous set download myminio/bbmovie-hls
      mc anonymous set download myminio/bbmovie-public
      
       # Register events
      mc event add myminio/bbmovie-raw arn:minio:sqs::_:nats --event put
      
      echo 'MinIO Setup Complete!';
      exit 0;
      "
  nats:
    image: nats:2.9-alpine
    container_name: nats_server
    command: >
      -js
      -DV
    ports:
      - "4222:4222"
      - "8222:8222" # for monitoring

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\\|yellow' || exit 1" ]
    deploy:
      resources:
        limits:
          memory: 2g

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  es_data:
  redis_data:
