version: '3.8'

services:
  mysql:
    env_file:
      - .env.mysql
    image: mysql:8.0
    command: --performance-schema=OFF --innodb-buffer-pool-size=128M
    container_name: shared_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.minio
    volumes:
      - C:/Users/buith_ejh62q2/Desktop/minio/data:/data
    command: server /data --console-address ":9001"
    depends_on:
      - nats
  minio-mc:
    image: minio/mc
    container_name: minio-setup
    env_file:
      - .env.minio-mc
    depends_on:
      - minio
    environment:
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}  
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./scripts/minio-init.sh:/minio-init.sh
    entrypoint: ["/bin/sh", "/minio-init.sh"]
  nats:
    image: nats:2.9-alpine
    container_name: nats_server
    command: >
      -js
      -DV
    ports:
      - "4222:4222"
      - "8222:8222" # for monitoring

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\\|yellow' || exit 1" ]
    deploy:
      resources:
        limits:
          memory: 2g

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  es_data:
  redis_data:
