app:
  jose:
    expiration:
      access-token: ${JOSE_EXPIRATION}
      refresh-token: ${JOSE_REFRESH_EXPIRATION}

  change-password-token-expiration-minutes: 15
  verification-token-expiration-minutes: 15

  otp-expiration-minutes: 1

  frontend:
    url: http://localhost:3000

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: auth
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: read:user,user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile,email
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: public_profile,email
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: identify,email
          x:
            client-id: ${X_CLIENT_ID}
            client-secret: ${X_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope:
              - users.read
              - tweet.read
        provider:
          github:
            user-info-uri: https://api.github.com/user
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id
          x:
            authorization-uri: https://x.com/i/oauth2/authorize
            token-uri: https://api.x.com/2/oauth2/token
            user-info-uri: https://api.x.com/2/users/me
            #Spring can't getActiveProvider nested data from JSON such as data.username => must implement custom service
            user-name-attribute: data
      authorizationserver:
          endpoint:
            jwk-set-uri: http://localhost:8080/.well-known/jwks.json

logging:
  level:
    org:
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      org.springframework.security: TRACE
      org.springframework.security.oauth2: TRACE
      org.springframework.web.client: DEBUG
      org.springframework.web.socket: DEBUG
      org.springframework.messaging: DEBUG
      elasticsearch: DEBUG
      springframework:
        security: DEBUG
        data:
          elasticsearch: DEBUG
        ai: DEBUG
    ai:
      djl: DEBUG

eureka:
  client:
    enabled: false # set to false if you don't want to register to eureka server
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


totp:
  digits: 6
  time-period: 60 # seconds
  algorithm: SHA1
  ntp:
    enabled: false
    server: pool.ntp.org
  qr.issuer: bbmovie-auth-service


server:
  port: 8080