spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth_route
              uri: lb://auth
              predicates:
                - Path=/api/auth/**
              metadata:
                public: true
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/auth(?<remaining>/.*)
                    replacement: /auth${remaining}
            - id: public_route
              uri: lb://movie-service
              predicates:
                - Path=/api/public/**
              metadata:
                public: true
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/public(?<remaining>/.*)
                    replacement: /public${remaining}
            - id: device_route
              uri: lb://auth
              predicates:
                - Path=/api/device/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/device(?<remaining>/.*)
                    replacement: /device${remaining}
            - id: jwks_route
              uri: lb://auth
              predicates:
                - Path=/.well-known/jwks.json
              metadata:
                public: true
              filters:
                - RewritePath=/.well-known/jwks.json, /.well-known/jwks.json
            - id: movie_route
              uri: lb://movie-service
              predicates:
                - Path=/api/movies/**,/api/reviews/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/(movies|reviews)(?<remaining>/.*)
                    replacement: /$1${remaining}
            - id: user_route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**,/api/payments/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/(users|payments)(?<remaining>/.*)
                    replacement: /$1${remaining}
          httpclient:
            response-timeout: 5s
            connect-timeout: 5000
          default-filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET, POST
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 5s
                  factor: 2
                  basedOnPreviousValue: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


internal:
  url:
    auth:
      base-url: lb://auth
      abac-endpoint: /auth/abac/new-access-token

logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG


server:
  port: 8765