spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth_route
              uri: lb://auth
              predicates:
                - Path=/api/auth/**,/api/device/**,/.well-known/jwks.json
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/(auth|device)(?<remaining>/.*)
                    replacement: /$1${remaining}
                - RewritePath=/.well-known/jwks.json, /.well-known/jwks.json
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5 # (5 requests per second)
                    redis-rate-limiter.burstCapacity: 10 # (allows temporary bursts up to 10 requests)
                    redis-rate-limiter.requestedTokens: 2
                    key-resolver: "#{@sidKeyResolver}"
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


internal:
  url:
    auth:
      base-url: lb://auth
      abac-endpoint: /auth/abac/new-access-token


server:
  port: 8765