spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          # Static routing => hardcode url => no scale
#          routes:
#            - id: auth
#              uri: http://localhost:8080
#              predicates:
#                - Path=/api/auth/**,/devices/**,/.well-known/**
#              filters:
#                -  StripPrefix=0
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              predicates:
                - Path="/api/{serviceId}/**"
              filters:
                - RewritePath="/api/(?<serviceId>[^/]+)(?<remaining>/.*)", "/${serviceId}${remaining}"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost


server:
  port: 8765