spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: oauth2_login_route
              uri: lb://auth
              predicates:
                - Path=/oauth2/**
              metadata:
                public: true
            - id: auth_route
              uri: lb://auth
              predicates:
                - Path=/api/auth/**
              metadata:
                public: true
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/auth(?<remaining>/.*)
                    replacement: /auth${remaining}
            - id: public_route
              uri: lb://movie-service
              predicates:
                - Path=/api/public/**
              metadata:
                public: true
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/public(?<remaining>/.*)
                    replacement: /public${remaining}
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@customKeyResolver}"
#                    # Rate: 60 requests/minute (60 req / 60s = 1 req/s)
#                    redis-rate-limiter.replenishRate: 1
#                    # Burst capacity allows for the full 60 requests to be made in a short burst.
#                    redis-rate-limiter.burstCapacity: 60
            - id: device_route
              uri: lb://auth
              predicates:
                - Path=/api/device/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/device(?<remaining>/.*)
                    replacement: /device${remaining}
            - id: jwks_route
              uri: lb://auth
              predicates:
                - Path=/.well-known/jwks.json
              metadata:
                public: true
              filters:
                - RewritePath=/.well-known/jwks.json, /.well-known/jwks.json
            - id: movie_route
              uri: lb://movie-service
              predicates:
                - Path=/api/movies/**,/api/reviews/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/(movies|reviews)(?<remaining>/.*)
                    replacement: /${remaining}
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@customKeyResolver}"
#                    # Rate: 3600 requests/hour (3600 req / 3600s = 1 req/s)
#                    redis-rate-limiter.replenishRate: 1
#                    # Burst capacity allows for the full 3600 requests to be made in a short burst.
#                    redis-rate-limiter.burstCapacity: 3600
            - id: user_route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**,/api/payments/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/(users|payments)(?<remaining>/.*)
                    replacement: /${remaining}
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@customKeyResolver}"
#                    # Rate: 86400 requests/day (86400 req / 86400s = 1 req/s)
#                    redis-rate-limiter.replenishRate: 1
#                    # Burst capacity allows for the full 86400 requests to be made in a short burst.
#                    redis-rate-limiter.burstCapacity: 86400
            - id: payment_route
              uri: lb://payment-service
              predicates:
                - Path=/api/payment/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/payment(?<remaining>/.*)
                    replacement: /api/payment${remaining}
            - id: subscription_route
              uri: lb://payment-service
              predicates:
                - Path=/api/subscription/**,/api/v1/subscription/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/(subscription|v1/subscription)(?<remaining>/.*)
                    replacement: /api/${remaining}
            - id: search_route
              uri: lb://bbmovie-search
              predicates:
                - Path=/api/search/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/search(?<remaining>/.*)
                    replacement: /search${remaining}
            - id: watchlist_route
              uri: lb://watchlist-quarkus
              predicates:
                - Path=/api/watchlist/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/watchlist(?<remaining>/.*)
                    replacement: /api/watchlist${remaining}
          httpclient:
            response-timeout: 5s
            connect-timeout: 5000
          default-filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET, POST, PUT, DELETE
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 5s
                  factor: 2
                  basedOnPreviousValue: true
          globalcors:
            cors-configurations:
              '[/**]':
                  allowedOrigins: "http://localhost:3000"
                  allowedMethods: "*"
                  allowedHeaders: "*"
                  allowCredentials: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

internal:
  url:
    auth:
      api-key: 1
      base-url: lb://auth
      abac-endpoint: /auth/abac/new-access-token

gateway:
  config:
    security:
      enabled: true
      api-key-header: X-Api-Key

ip:
  ipinfo:
    token: ${IP_INFO_TOKEN}
  vpnapi:
    api-key: ${VNP_API_API_KEY}
  ipapi:
    api-key: ${IP_API_KEY}

logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG
    org.springframework.cloud.gateway.filter.ratelimit.RedisRateLimiter: DEBUG
    Bucket4j: DEBUG

server:
  port: 8765
