spring:
  application:
    name: gateway
  #  cloud:
  #    gateway:
  #      server:
  #        webflux:
  #          discovery:
  #            locator:
  #              enabled: true
  #              lower-case-service-id: true
  #          routes:
  #            - id: auth_route
  #              uri: lb://auth
  #              predicates:
  #                - Path=/api/auth/**,/api/device/**,/.well-known/jwks.json
  #              filters:
  #                - name: RewritePath
  #                  args:
  #                    regexp: /api/(auth|device)(?<remaining>/.*)
  #                    replacement: /$1${remaining}
  #                - RewritePath=/.well-known/jwks.json, /.well-known/jwks.json
  #                - name: RequestRateLimiter
  #                  args:
  #                    redis-rate-limiter.replenishRate: 5 # (5 requests per second)
  #                    redis-rate-limiter.burstCapacity: 10 # (allows temporary bursts up to 10 requests)
  #                    redis-rate-limiter.requestedTokens: 2
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth_route
              uri: lb://auth
              predicates:
                - Path=/api/auth/**
              metadata:
                public: true
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/auth(?<remaining>/.*)
                    replacement: /auth${remaining}
#                - name: RequestRateLimiter
#                  args:
#                    rate-limiter: "#{@abacRedisRateLimiter}"
#                    key-resolver: "#{@sidKeyResolver}"
            - id: public_route
              uri: lb://movie-service
              predicates:
                - Path=/api/public/**
              metadata:
                public: true
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/public(?<remaining>/.*)
                    replacement: /public${remaining}
#                - name: RequestRateLimiter
#                  args:
#                    rate-limiter: "#{@abacRedisRateLimiter}"
#                    key-resolver: "#{@sidKeyResolver}"
            - id: device_route
              uri: lb://auth
              predicates:
                - Path=/api/device/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/device(?<remaining>/.*)
                    replacement: /device${remaining}
#                - name: RequestRateLimiter
#                  args:
#                    rate-limiter: "#{@abacRedisRateLimiter}"
#                    key-resolver: "#{@sidKeyResolver}"
            - id: jwks_route
              uri: lb://auth
              predicates:
                - Path=/.well-known/jwks.json
              metadata:
                public: true
              filters:
                - RewritePath=/.well-known/jwks.json, /.well-known/jwks.json
            - id: movie_route
              uri: lb://movie-service
              predicates:
                - Path=/api/movies/**,/api/reviews/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/(movies|reviews)(?<remaining>/.*)
                    replacement: /$1${remaining}
#                - name: RequestRateLimiter
#                  args:
#                    rate-limiter: "#{@abacRedisRateLimiter}"
#                    key-resolver: "#{@sidKeyResolver}"
            - id: user_route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**,/api/payments/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /api/(users|payments)(?<remaining>/.*)
                    replacement: /$1${remaining}
#                - name: RequestRateLimiter
#                  args:
#                    rate-limiter: "#{@abacRedisRateLimiter}"
#                    key-resolver: "#{@sidKeyResolver}"
  data:
    redis:
      host: localhost
      port: 6379
      database: 0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


internal:
  url:
    auth:
      base-url: lb://auth
      abac-endpoint: /auth/abac/new-access-token

logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG


server:
  port: 8765