spring:
  application:
    name: bbmovie-upload-file
  upload-dir: ${UPLOAD_DIR}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  sql:
    init:
      mode: always


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG
#    org.springframework.r2dbc.core: DEBUG
#    io:
#      asyncer:
#        r2dbc:
#          mysql: debug


management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, *
  metrics:
    tags:
      application: ${spring.application.name}


ffmpeg.path: ${FFMPEG_PATH}
ffprobe.path: ${FFPROBE_PATH}
app.upload.temp-dir: C:/upload-temp


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


jose:
  jwk:
    endpoint: http://localhost:8080/.well-known/jwks.json


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


server:
  port: 8081
