app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-milliseconds: ${JWT_EXPIRATION}
  jwt-refresh-expiration-milliseconds: ${JWT_REFRESH_EXPIRATION}

  change-password-token-expiration-minutes: 15
  verification-token-expiration-minutes: 15

  otp-expiration-minutes: 1

  frontend:
    url: http://localhost:3000


github:
  webhook:
    secret: ${GITHUB_WEBHOOK_SECRET}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 10MB
  #  ssl:
#    bundle:
#      pem:
#        server:
#          keystore:
#            certificate: ${SERVER_CERTIFICATE}
#            private-key: ${SERVER_PRIVATE_KEY}
#            private-key-password: ${SERVER_PRIVATE_KEY_PASSWORD}
#          reload-on-update: ${SERVER_RELOAD_ON_UPDATE}

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
    connection-timeout: 10s
    socket-timeout: 10s

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/github"
            scope: read:user,user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope: profile,email
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/facebook"
            scope: public_profile,email
        provider:
          github:
            user-info-uri: https://api.github.com/user
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email

  ai:
    vectorstore:
      elasticsearch:
        index-name: "movies"


#Data encrypt/decrypt
#database:
#  secret-key-password: ${DATABASE_SECRET_KEY_PASSWORD}
#  database.algorithm: ${DATABASE_ALGORITHM}
#  database.secret-factory.algorithm: ${DATABASE_SECRET_FACTORY_ALGORITHM}
#  database.salt: ${DATABASE_SALT}
#  database.iterations: ${DATABASE_ITERATIONS}

#Twilio
#twilio:
#  account-sid: ${TWILIO_ACCOUNT_SID}
#  auth-token: ${TWILIO_AUTH_TOKEN}
#  phone-number: ${TWILIO_PHONE_NUMBER}
#  verification.service.sid: ${TWILIO_SERVICE_SID}


logging:
  level:
    org:
      elasticsearch: DEBUG
      springframework:
        security: DEBUG
        data:
          elasticsearch: DEBUG
        ai: DEBUG
    ai:
      djl: DEBUG


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


huggingface:
  api:
    key: ${HUGGING_FACE_BBMOVIE_API_KEY}


server:
#  ssl:
#    bundle: ${SERVER_SSL_BUNDLE}
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css


management:
  endpoint:
    shutdown:
      access: none